export const RUTE_POKEMONS = "http://localhost:3001/api/pokemon"
export const RUTE_DATA= "http://localhost:3001/api/pokemon/"
export const RUTE_NAME= "http://localhost:3001/api/pokemon?name="
export const RUTE_POKEMONSDB = "http://localhost:3001/api/pokemon/db"
export const RUTE_POKEMONSAPI = "http://localhost:3001/api/pokemon/api"
export const RUTE_TYPE = "http://localhost:3001/api/type"